version: '2.1'

services:
  authority0:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.3 
  authority1:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.4 

  client0:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.85
  client1:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.86 



networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.1/24
        gateway: 10.0.0.1

