version: '2.1'

services:
  authority0:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.3 
  authority1:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.4
  authority2:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.5 
  authority3:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.6


  client0:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.85
  client1:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.86
  client2:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.87
  client3:
    image: bbtest
    command:
      /root/start.sh
    networks:
      app_net:
        ipv4_address: 10.0.0.88

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.1/24
        gateway: 10.0.0.1

